packages:
  - 'packages/activity'
  - 'packages/client'
  - 'packages/cloud'
  - 'packages/common'
  - 'packages/core-bridge'
  - 'packages/create-project'
  - 'packages/envconfig'
  - 'packages/interceptors-opentelemetry'
  - 'packages/meta'
  - 'packages/nexus'
  - 'packages/nyc-test-coverage'
  - 'packages/plugin'
  - 'packages/proto'
  - 'packages/test'
  - 'packages/testing'
  - 'packages/worker'
  - 'packages/workflow'

# Only allow installing packages that are at least a day old
minimumReleaseAge: 1440
# Allow depending on just published Temporal packages
minimumReleaseAgeExclude:
  - '@temporalio/*'
  - 'nexus-rpc'

ignoreScripts: true
