packages:
  - packages/activity
  - packages/ai-sdk
  - packages/client
  - packages/cloud
  - packages/common
  - packages/core-bridge
  - packages/create-project
  - packages/envconfig
  - packages/interceptors-opentelemetry
  - packages/lambda-worker
  - packages/meta
  - packages/nexus
  - packages/nyc-test-coverage
  - packages/plugin
  - packages/proto
  - packages/test
  - packages/testing
  - packages/worker
  - packages/workflow
  - scripts

ignoreScripts: true

# Minimum release age, in minutes (1 day)
minimumReleaseAge: 1440

# Allow depending on just published Temporal packages
minimumReleaseAgeExclude:
  - '@temporalio/*'
  - nexus-rpc

peerDependencyRules:
  ignoreMissing:
    # Peer of json-joy@9.9.1, missing in memfs@4.6.0
    # No apparent issue at runtime if not present
    - quill-delta

overrides:
  'minimatch@>=7.0.0 <7.4.8': '>=7.4.8'
  serialize-javascript: '>=7.0.3'
  handlebars: '>=4.7.9'

patchedDependencies:
  protobufjs@7.5.5: patches/protobufjs@7.5.5.patch
