packages:
  - packages/activity
  - packages/ai-sdk
  - packages/client
  - packages/cloud
  - packages/common
  - packages/core-bridge
  - packages/create-project
  - packages/envconfig
  - packages/interceptors-opentelemetry
  - packages/meta
  - packages/nexus
  - packages/nyc-test-coverage
  - packages/plugin
  - packages/proto
  - packages/test
  - packages/testing
  - packages/worker
  - packages/workflow

ignoreScripts: true

minimumReleaseAge: 1440

# Allow depending on just published Temporal packages
minimumReleaseAgeExclude:
  - '@temporalio/*'
  - nexus-rpc
  - ai
  - '@ai-sdk/*'

peerDependencyRules:
  ignoreMissing:
    # Peer of json-joy@9.9.1, missing in memfs@4.6.0
    # No apparent issue at runtime if not present
    - quill-delta
