// Code generated by packages/proto/scripts/gen-payload-visitor.ts. DO NOT EDIT.

import type { coresdk, temporal } from '../protos/root';

type Payload = temporal.api.common.v1.IPayload;

export interface WalkEnv<Ctx> {
  transformPayload(payload: Payload, context: Ctx): Promise<Payload>;
  transformPayloads(payloads: Payload[], context: Ctx): Promise<Payload[]>;
  deriveContext?(message: object, typeName: string, context: Ctx): Ctx;
  skipHeaders: boolean;
  skipSearchAttributes: boolean;
}

export function walkActivityTask<Ctx>(
  root: coresdk.activity_task.IActivityTask,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_activity_task_ActivityTask(root, env, context, pending);
  return pending;
}

export function walkActivityHeartbeat<Ctx>(
  root: coresdk.IActivityHeartbeat,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_ActivityHeartbeat(root, env, context, pending);
  return pending;
}

export function walkActivityTaskCompletion<Ctx>(
  root: coresdk.IActivityTaskCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_ActivityTaskCompletion(root, env, context, pending);
  return pending;
}

export function walkNexusTask<Ctx>(
  root: coresdk.nexus.INexusTask,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_nexus_NexusTask(root, env, context, pending);
  return pending;
}

export function walkNexusTaskCompletion<Ctx>(
  root: coresdk.nexus.INexusTaskCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_nexus_NexusTaskCompletion(root, env, context, pending);
  return pending;
}

export function walkWorkflowActivation<Ctx>(
  root: coresdk.workflow_activation.IWorkflowActivation,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_workflow_activation_WorkflowActivation(root, env, context, pending);
  return pending;
}

export function walkWorkflowActivationCompletion<Ctx>(
  root: coresdk.workflow_completion.IWorkflowActivationCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_workflow_completion_WorkflowActivationCompletion(root, env, context, pending);
  return pending;
}

function walk_coresdk_activity_result_ActivityExecutionResult<Ctx>(
  o: coresdk.activity_result.IActivityExecutionResult,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.activity_result.ActivityExecutionResult', context)
    : context;
  {
    const c = o.completed;
    if (c != null) walk_coresdk_activity_result_Success(c, env, ctx, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_activity_result_Failure(c, env, ctx, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_activity_result_Cancellation(c, env, ctx, pending);
  }
}

function walk_coresdk_activity_result_ActivityResolution<Ctx>(
  o: coresdk.activity_result.IActivityResolution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_result.ActivityResolution', context) : context;
  {
    const c = o.completed;
    if (c != null) walk_coresdk_activity_result_Success(c, env, ctx, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_activity_result_Failure(c, env, ctx, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_activity_result_Cancellation(c, env, ctx, pending);
  }
}

function walk_coresdk_activity_result_Cancellation<Ctx>(
  o: coresdk.activity_result.ICancellation,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_result.Cancellation', context) : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_activity_result_Failure<Ctx>(
  o: coresdk.activity_result.IFailure,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_result.Failure', context) : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_activity_result_Success<Ctx>(
  o: coresdk.activity_result.ISuccess,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_result.Success', context) : context;
  {
    const p = o.result;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.result = r;
        })
      );
  }
}

function walk_coresdk_activity_task_ActivityTask<Ctx>(
  o: coresdk.activity_task.IActivityTask,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_task.ActivityTask', context) : context;
  {
    const c = o.start;
    if (c != null) walk_coresdk_activity_task_Start(c, env, ctx, pending);
  }
}

function walk_coresdk_activity_task_Start<Ctx>(
  o: coresdk.activity_task.IStart,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.activity_task.Start', context) : context;
  {
    const m = o.headerFields;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          env.transformPayload(v, ctx).then((r) => {
            m[k] = r;
          })
        );
  }
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.input = r;
        })
      );
  }
  {
    const a = o.heartbeatDetails;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.heartbeatDetails = r;
        })
      );
  }
}

function walk_coresdk_ActivityHeartbeat<Ctx>(
  o: coresdk.IActivityHeartbeat,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.ActivityHeartbeat', context) : context;
  {
    const a = o.details;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.details = r;
        })
      );
  }
}

function walk_coresdk_ActivityTaskCompletion<Ctx>(
  o: coresdk.IActivityTaskCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.ActivityTaskCompletion', context) : context;
  {
    const c = o.result;
    if (c != null) walk_coresdk_activity_result_ActivityExecutionResult(c, env, ctx, pending);
  }
}

function walk_coresdk_child_workflow_Cancellation<Ctx>(
  o: coresdk.child_workflow.ICancellation,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.child_workflow.Cancellation', context) : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_child_workflow_ChildWorkflowResult<Ctx>(
  o: coresdk.child_workflow.IChildWorkflowResult,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.child_workflow.ChildWorkflowResult', context) : context;
  {
    const c = o.completed;
    if (c != null) walk_coresdk_child_workflow_Success(c, env, ctx, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_child_workflow_Failure(c, env, ctx, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_child_workflow_Cancellation(c, env, ctx, pending);
  }
}

function walk_coresdk_child_workflow_Failure<Ctx>(
  o: coresdk.child_workflow.IFailure,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.child_workflow.Failure', context) : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_child_workflow_Success<Ctx>(
  o: coresdk.child_workflow.ISuccess,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.child_workflow.Success', context) : context;
  {
    const p = o.result;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.result = r;
        })
      );
  }
}

function walk_coresdk_nexus_NexusOperationResult<Ctx>(
  o: coresdk.nexus.INexusOperationResult,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.nexus.NexusOperationResult', context) : context;
  {
    const p = o.completed;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.completed = r;
        })
      );
  }
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
  {
    const c = o.timedOut;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_nexus_NexusTask<Ctx>(
  o: coresdk.nexus.INexusTask,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.nexus.NexusTask', context) : context;
  {
    const c = o.task;
    if (c != null) walk_temporal_api_workflowservice_v1_PollNexusTaskQueueResponse(c, env, ctx, pending);
  }
}

function walk_coresdk_nexus_NexusTaskCompletion<Ctx>(
  o: coresdk.nexus.INexusTaskCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.nexus.NexusTaskCompletion', context) : context;
  {
    const c = o.completed;
    if (c != null) walk_temporal_api_nexus_v1_Response(c, env, ctx, pending);
  }
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_DoUpdate<Ctx>(
  o: coresdk.workflow_activation.IDoUpdate,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_activation.DoUpdate', context) : context;
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.input = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
}

function walk_coresdk_workflow_activation_InitializeWorkflow<Ctx>(
  o: coresdk.workflow_activation.IInitializeWorkflow,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.InitializeWorkflow', context)
    : context;
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.arguments = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
  {
    const c = o.continuedFailure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
  {
    const c = o.lastCompletionResult;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, env, ctx, pending);
  }
  {
    const c = o.memo;
    if (c != null) walk_temporal_api_common_v1_Memo(c, env, ctx, pending);
  }
  {
    if (!env.skipSearchAttributes) {
      const c = o.searchAttributes;
      if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, env, ctx, pending);
    }
  }
}

function walk_coresdk_workflow_activation_QueryWorkflow<Ctx>(
  o: coresdk.workflow_activation.IQueryWorkflow,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_activation.QueryWorkflow', context) : context;
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.arguments = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
}

function walk_coresdk_workflow_activation_ResolveActivity<Ctx>(
  o: coresdk.workflow_activation.IResolveActivity,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveActivity', context)
    : context;
  {
    const c = o.result;
    if (c != null) walk_coresdk_activity_result_ActivityResolution(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecution<Ctx>(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveChildWorkflowExecution', context)
    : context;
  {
    const c = o.result;
    if (c != null) walk_coresdk_child_workflow_ChildWorkflowResult(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStart<Ctx>(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecutionStart,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveChildWorkflowExecutionStart', context)
    : context;
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStartCancelled(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStartCancelled<Ctx>(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecutionStartCancelled,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveChildWorkflowExecutionStartCancelled', context)
    : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveNexusOperation<Ctx>(
  o: coresdk.workflow_activation.IResolveNexusOperation,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveNexusOperation', context)
    : context;
  {
    const c = o.result;
    if (c != null) walk_coresdk_nexus_NexusOperationResult(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveNexusOperationStart<Ctx>(
  o: coresdk.workflow_activation.IResolveNexusOperationStart,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveNexusOperationStart', context)
    : context;
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveRequestCancelExternalWorkflow<Ctx>(
  o: coresdk.workflow_activation.IResolveRequestCancelExternalWorkflow,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveRequestCancelExternalWorkflow', context)
    : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveSignalExternalWorkflow<Ctx>(
  o: coresdk.workflow_activation.IResolveSignalExternalWorkflow,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.ResolveSignalExternalWorkflow', context)
    : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_SignalWorkflow<Ctx>(
  o: coresdk.workflow_activation.ISignalWorkflow,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_activation.SignalWorkflow', context) : context;
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.input = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
}

function walk_coresdk_workflow_activation_WorkflowActivation<Ctx>(
  o: coresdk.workflow_activation.IWorkflowActivation,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.WorkflowActivation', context)
    : context;
  {
    const a = o.jobs;
    if (a) for (const v of a) walk_coresdk_workflow_activation_WorkflowActivationJob(v, env, ctx, pending);
  }
}

function walk_coresdk_workflow_activation_WorkflowActivationJob<Ctx>(
  o: coresdk.workflow_activation.IWorkflowActivationJob,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_activation.WorkflowActivationJob', context)
    : context;
  {
    const c = o.initializeWorkflow;
    if (c != null) walk_coresdk_workflow_activation_InitializeWorkflow(c, env, ctx, pending);
  }
  {
    const c = o.queryWorkflow;
    if (c != null) walk_coresdk_workflow_activation_QueryWorkflow(c, env, ctx, pending);
  }
  {
    const c = o.signalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_SignalWorkflow(c, env, ctx, pending);
  }
  {
    const c = o.resolveActivity;
    if (c != null) walk_coresdk_workflow_activation_ResolveActivity(c, env, ctx, pending);
  }
  {
    const c = o.resolveChildWorkflowExecutionStart;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStart(c, env, ctx, pending);
  }
  {
    const c = o.resolveChildWorkflowExecution;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.resolveSignalExternalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_ResolveSignalExternalWorkflow(c, env, ctx, pending);
  }
  {
    const c = o.resolveRequestCancelExternalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_ResolveRequestCancelExternalWorkflow(c, env, ctx, pending);
  }
  {
    const c = o.doUpdate;
    if (c != null) walk_coresdk_workflow_activation_DoUpdate(c, env, ctx, pending);
  }
  {
    const c = o.resolveNexusOperationStart;
    if (c != null) walk_coresdk_workflow_activation_ResolveNexusOperationStart(c, env, ctx, pending);
  }
  {
    const c = o.resolveNexusOperation;
    if (c != null) walk_coresdk_workflow_activation_ResolveNexusOperation(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_commands_CompleteWorkflowExecution<Ctx>(
  o: coresdk.workflow_commands.ICompleteWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.CompleteWorkflowExecution', context)
    : context;
  {
    const p = o.result;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.result = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_ContinueAsNewWorkflowExecution<Ctx>(
  o: coresdk.workflow_commands.IContinueAsNewWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.ContinueAsNewWorkflowExecution', context)
    : context;
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.arguments = r;
        })
      );
  }
  {
    const m = o.memo;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          env.transformPayload(v, ctx).then((r) => {
            m[k] = r;
          })
        );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
  {
    if (!env.skipSearchAttributes) {
      const c = o.searchAttributes;
      if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, env, ctx, pending);
    }
  }
}

function walk_coresdk_workflow_commands_FailWorkflowExecution<Ctx>(
  o: coresdk.workflow_commands.IFailWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.FailWorkflowExecution', context)
    : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_commands_ModifyWorkflowProperties<Ctx>(
  o: coresdk.workflow_commands.IModifyWorkflowProperties,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.ModifyWorkflowProperties', context)
    : context;
  {
    const c = o.upsertedMemo;
    if (c != null) walk_temporal_api_common_v1_Memo(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_commands_QueryResult<Ctx>(
  o: coresdk.workflow_commands.IQueryResult,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_commands.QueryResult', context) : context;
  {
    const c = o.succeeded;
    if (c != null) walk_coresdk_workflow_commands_QuerySuccess(c, env, ctx, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_commands_QuerySuccess<Ctx>(
  o: coresdk.workflow_commands.IQuerySuccess,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_commands.QuerySuccess', context) : context;
  {
    const p = o.response;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.response = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleActivity<Ctx>(
  o: coresdk.workflow_commands.IScheduleActivity,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_commands.ScheduleActivity', context) : context;
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.arguments = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleLocalActivity<Ctx>(
  o: coresdk.workflow_commands.IScheduleLocalActivity,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.ScheduleLocalActivity', context)
    : context;
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.arguments = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleNexusOperation<Ctx>(
  o: coresdk.workflow_commands.IScheduleNexusOperation,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.ScheduleNexusOperation', context)
    : context;
  {
    const p = o.input;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.input = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_SignalExternalWorkflowExecution<Ctx>(
  o: coresdk.workflow_commands.ISignalExternalWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.SignalExternalWorkflowExecution', context)
    : context;
  {
    const a = o.args;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.args = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
}

function walk_coresdk_workflow_commands_StartChildWorkflowExecution<Ctx>(
  o: coresdk.workflow_commands.IStartChildWorkflowExecution,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.StartChildWorkflowExecution', context)
    : context;
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.input = r;
        })
      );
  }
  {
    if (!env.skipHeaders) {
      const m = o.headers;
      if (m)
        for (const [k, v] of Object.entries(m))
          pending.push(
            env.transformPayload(v, ctx).then((r) => {
              m[k] = r;
            })
          );
    }
  }
  {
    const m = o.memo;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          env.transformPayload(v, ctx).then((r) => {
            m[k] = r;
          })
        );
  }
  {
    if (!env.skipSearchAttributes) {
      const c = o.searchAttributes;
      if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, env, ctx, pending);
    }
  }
}

function walk_coresdk_workflow_commands_UpdateResponse<Ctx>(
  o: coresdk.workflow_commands.IUpdateResponse,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_commands.UpdateResponse', context) : context;
  {
    const c = o.rejected;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
  {
    const p = o.completed;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.completed = r;
        })
      );
  }
}

function walk_coresdk_workflow_commands_UpsertWorkflowSearchAttributes<Ctx>(
  o: coresdk.workflow_commands.IUpsertWorkflowSearchAttributes,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_commands.UpsertWorkflowSearchAttributes', context)
    : context;
  {
    if (!env.skipSearchAttributes) {
      const c = o.searchAttributes;
      if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, env, ctx, pending);
    }
  }
}

function walk_coresdk_workflow_commands_WorkflowCommand<Ctx>(
  o: coresdk.workflow_commands.IWorkflowCommand,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_commands.WorkflowCommand', context) : context;
  {
    const c = o.userMetadata;
    if (c != null) walk_temporal_api_sdk_v1_UserMetadata(c, env, ctx, pending);
  }
  {
    const c = o.scheduleActivity;
    if (c != null) walk_coresdk_workflow_commands_ScheduleActivity(c, env, ctx, pending);
  }
  {
    const c = o.respondToQuery;
    if (c != null) walk_coresdk_workflow_commands_QueryResult(c, env, ctx, pending);
  }
  {
    const c = o.completeWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_CompleteWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.failWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_FailWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.continueAsNewWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_ContinueAsNewWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.startChildWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_StartChildWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.signalExternalWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_SignalExternalWorkflowExecution(c, env, ctx, pending);
  }
  {
    const c = o.scheduleLocalActivity;
    if (c != null) walk_coresdk_workflow_commands_ScheduleLocalActivity(c, env, ctx, pending);
  }
  {
    const c = o.upsertWorkflowSearchAttributes;
    if (c != null) walk_coresdk_workflow_commands_UpsertWorkflowSearchAttributes(c, env, ctx, pending);
  }
  {
    const c = o.modifyWorkflowProperties;
    if (c != null) walk_coresdk_workflow_commands_ModifyWorkflowProperties(c, env, ctx, pending);
  }
  {
    const c = o.updateResponse;
    if (c != null) walk_coresdk_workflow_commands_UpdateResponse(c, env, ctx, pending);
  }
  {
    const c = o.scheduleNexusOperation;
    if (c != null) walk_coresdk_workflow_commands_ScheduleNexusOperation(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_completion_Failure<Ctx>(
  o: coresdk.workflow_completion.IFailure,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_completion.Failure', context) : context;
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_coresdk_workflow_completion_Success<Ctx>(
  o: coresdk.workflow_completion.ISuccess,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'coresdk.workflow_completion.Success', context) : context;
  {
    const a = o.commands;
    if (a) for (const v of a) walk_coresdk_workflow_commands_WorkflowCommand(v, env, ctx, pending);
  }
}

function walk_coresdk_workflow_completion_WorkflowActivationCompletion<Ctx>(
  o: coresdk.workflow_completion.IWorkflowActivationCompletion,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'coresdk.workflow_completion.WorkflowActivationCompletion', context)
    : context;
  {
    const c = o.successful;
    if (c != null) walk_coresdk_workflow_completion_Success(c, env, ctx, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_workflow_completion_Failure(c, env, ctx, pending);
  }
}

function walk_temporal_api_common_v1_Memo<Ctx>(
  o: temporal.api.common.v1.IMemo,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.common.v1.Memo', context) : context;
  {
    const m = o.fields;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          env.transformPayload(v, ctx).then((r) => {
            m[k] = r;
          })
        );
  }
}

function walk_temporal_api_common_v1_Payloads<Ctx>(
  o: temporal.api.common.v1.IPayloads,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.common.v1.Payloads', context) : context;
  {
    const a = o.payloads;
    if (a && a.length)
      pending.push(
        env.transformPayloads(a, ctx).then((r) => {
          o.payloads = r;
        })
      );
  }
}

function walk_temporal_api_common_v1_SearchAttributes<Ctx>(
  o: temporal.api.common.v1.ISearchAttributes,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.common.v1.SearchAttributes', context) : context;
  {
    const m = o.indexedFields;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          env.transformPayload(v, ctx).then((r) => {
            m[k] = r;
          })
        );
  }
}

function walk_temporal_api_failure_v1_ApplicationFailureInfo<Ctx>(
  o: temporal.api.failure.v1.IApplicationFailureInfo,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.failure.v1.ApplicationFailureInfo', context)
    : context;
  {
    const c = o.details;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, env, ctx, pending);
  }
}

function walk_temporal_api_failure_v1_CanceledFailureInfo<Ctx>(
  o: temporal.api.failure.v1.ICanceledFailureInfo,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.failure.v1.CanceledFailureInfo', context)
    : context;
  {
    const c = o.details;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, env, ctx, pending);
  }
}

function walk_temporal_api_failure_v1_Failure<Ctx>(
  o: temporal.api.failure.v1.IFailure,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.failure.v1.Failure', context) : context;
  {
    const p = o.encodedAttributes;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.encodedAttributes = r;
        })
      );
  }
  {
    const c = o.cause;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
  {
    const c = o.applicationFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_ApplicationFailureInfo(c, env, ctx, pending);
  }
  {
    const c = o.timeoutFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_TimeoutFailureInfo(c, env, ctx, pending);
  }
  {
    const c = o.canceledFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_CanceledFailureInfo(c, env, ctx, pending);
  }
  {
    const c = o.resetWorkflowFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_ResetWorkflowFailureInfo(c, env, ctx, pending);
  }
}

function walk_temporal_api_failure_v1_ResetWorkflowFailureInfo<Ctx>(
  o: temporal.api.failure.v1.IResetWorkflowFailureInfo,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.failure.v1.ResetWorkflowFailureInfo', context)
    : context;
  {
    const c = o.lastHeartbeatDetails;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, env, ctx, pending);
  }
}

function walk_temporal_api_failure_v1_TimeoutFailureInfo<Ctx>(
  o: temporal.api.failure.v1.ITimeoutFailureInfo,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.failure.v1.TimeoutFailureInfo', context) : context;
  {
    const c = o.lastHeartbeatDetails;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, env, ctx, pending);
  }
}

function walk_temporal_api_nexus_v1_Request<Ctx>(
  o: temporal.api.nexus.v1.IRequest,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.nexus.v1.Request', context) : context;
  {
    const c = o.startOperation;
    if (c != null) walk_temporal_api_nexus_v1_StartOperationRequest(c, env, ctx, pending);
  }
}

function walk_temporal_api_nexus_v1_Response<Ctx>(
  o: temporal.api.nexus.v1.IResponse,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.nexus.v1.Response', context) : context;
  {
    const c = o.startOperation;
    if (c != null) walk_temporal_api_nexus_v1_StartOperationResponse(c, env, ctx, pending);
  }
}

function walk_temporal_api_nexus_v1_StartOperationRequest<Ctx>(
  o: temporal.api.nexus.v1.IStartOperationRequest,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.nexus.v1.StartOperationRequest', context)
    : context;
  {
    const p = o.payload;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.payload = r;
        })
      );
  }
}

function walk_temporal_api_nexus_v1_StartOperationResponse<Ctx>(
  o: temporal.api.nexus.v1.IStartOperationResponse,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.nexus.v1.StartOperationResponse', context)
    : context;
  {
    const c = o.syncSuccess;
    if (c != null) walk_temporal_api_nexus_v1_StartOperationResponse_Sync(c, env, ctx, pending);
  }
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, env, ctx, pending);
  }
}

function walk_temporal_api_nexus_v1_StartOperationResponse_Sync<Ctx>(
  o: temporal.api.nexus.v1.StartOperationResponse.ISync,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.nexus.v1.StartOperationResponse.Sync', context)
    : context;
  {
    const p = o.payload;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.payload = r;
        })
      );
  }
}

function walk_temporal_api_sdk_v1_UserMetadata<Ctx>(
  o: temporal.api.sdk.v1.IUserMetadata,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext ? env.deriveContext(o, 'temporal.api.sdk.v1.UserMetadata', context) : context;
  {
    const p = o.summary;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.summary = r;
        })
      );
  }
  {
    const p = o.details;
    if (p != null)
      pending.push(
        env.transformPayload(p, ctx).then((r) => {
          o.details = r;
        })
      );
  }
}

function walk_temporal_api_workflowservice_v1_PollNexusTaskQueueResponse<Ctx>(
  o: temporal.api.workflowservice.v1.IPollNexusTaskQueueResponse,
  env: WalkEnv<Ctx>,
  context: Ctx,
  pending: Promise<unknown>[]
): void {
  const ctx = env.deriveContext
    ? env.deriveContext(o, 'temporal.api.workflowservice.v1.PollNexusTaskQueueResponse', context)
    : context;
  {
    const c = o.request;
    if (c != null) walk_temporal_api_nexus_v1_Request(c, env, ctx, pending);
  }
}
