/* eslint-disable */
// Code generated by packages/proto/scripts/gen-payload-visitor.ts. DO NOT EDIT.

import type { coresdk, temporal } from '../protos/root';

type Payload = temporal.api.common.v1.IPayload;
type Visit = (payloads: Payload[], abortSignal?: AbortSignal) => Promise<Payload[]>;

function one(payloads: Payload[]): Payload {
  if (payloads.length !== 1) {
    throw new Error(`payload visitor: a singular field transform returned ${payloads.length} payloads, expected 1`);
  }
  return payloads[0]!;
}

function many(payloads: Payload[], expected: number): Payload[] {
  if (payloads.length !== expected) {
    throw new Error(
      `payload visitor: a repeated field transform returned ${payloads.length} payloads, expected ${expected}`
    );
  }
  return payloads;
}

export function walkWorkflowActivation(
  root: coresdk.workflow_activation.IWorkflowActivation,
  visit: Visit
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_workflow_activation_WorkflowActivation(root, visit, pending);
  return pending;
}

export function walkWorkflowActivationCompletion(
  root: coresdk.workflow_completion.IWorkflowActivationCompletion,
  visit: Visit
): Promise<unknown>[] {
  const pending: Promise<unknown>[] = [];
  walk_coresdk_workflow_completion_WorkflowActivationCompletion(root, visit, pending);
  return pending;
}

function walk_coresdk_activity_result_ActivityResolution(
  o: coresdk.activity_result.IActivityResolution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.completed;
    if (c != null) walk_coresdk_activity_result_Success(c, visit, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_activity_result_Failure(c, visit, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_activity_result_Cancellation(c, visit, pending);
  }
}

function walk_coresdk_activity_result_Cancellation(
  o: coresdk.activity_result.ICancellation,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_activity_result_Failure(
  o: coresdk.activity_result.IFailure,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_activity_result_Success(
  o: coresdk.activity_result.ISuccess,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.result;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.result = one(r);
        })
      );
  }
}

function walk_coresdk_child_workflow_Cancellation(
  o: coresdk.child_workflow.ICancellation,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_child_workflow_ChildWorkflowResult(
  o: coresdk.child_workflow.IChildWorkflowResult,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.completed;
    if (c != null) walk_coresdk_child_workflow_Success(c, visit, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_child_workflow_Failure(c, visit, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_child_workflow_Cancellation(c, visit, pending);
  }
}

function walk_coresdk_child_workflow_Failure(
  o: coresdk.child_workflow.IFailure,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_child_workflow_Success(
  o: coresdk.child_workflow.ISuccess,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.result;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.result = one(r);
        })
      );
  }
}

function walk_coresdk_nexus_NexusOperationResult(
  o: coresdk.nexus.INexusOperationResult,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.completed;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.completed = one(r);
        })
      );
  }
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
  {
    const c = o.cancelled;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
  {
    const c = o.timedOut;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_DoUpdate(
  o: coresdk.workflow_activation.IDoUpdate,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.input = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_coresdk_workflow_activation_InitializeWorkflow(
  o: coresdk.workflow_activation.IInitializeWorkflow,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.arguments = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const c = o.continuedFailure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
  {
    const c = o.lastCompletionResult;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, visit, pending);
  }
  {
    const c = o.memo;
    if (c != null) walk_temporal_api_common_v1_Memo(c, visit, pending);
  }
  {
    const c = o.searchAttributes;
    if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_QueryWorkflow(
  o: coresdk.workflow_activation.IQueryWorkflow,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.arguments = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_coresdk_workflow_activation_ResolveActivity(
  o: coresdk.workflow_activation.IResolveActivity,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.result;
    if (c != null) walk_coresdk_activity_result_ActivityResolution(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecution(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.result;
    if (c != null) walk_coresdk_child_workflow_ChildWorkflowResult(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStart(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecutionStart,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.cancelled;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStartCancelled(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStartCancelled(
  o: coresdk.workflow_activation.IResolveChildWorkflowExecutionStartCancelled,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveNexusOperation(
  o: coresdk.workflow_activation.IResolveNexusOperation,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.result;
    if (c != null) walk_coresdk_nexus_NexusOperationResult(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveNexusOperationStart(
  o: coresdk.workflow_activation.IResolveNexusOperationStart,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveRequestCancelExternalWorkflow(
  o: coresdk.workflow_activation.IResolveRequestCancelExternalWorkflow,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_ResolveSignalExternalWorkflow(
  o: coresdk.workflow_activation.IResolveSignalExternalWorkflow,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_activation_SignalWorkflow(
  o: coresdk.workflow_activation.ISignalWorkflow,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.input = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_coresdk_workflow_activation_WorkflowActivation(
  o: coresdk.workflow_activation.IWorkflowActivation,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.jobs;
    if (a) for (const v of a) walk_coresdk_workflow_activation_WorkflowActivationJob(v, visit, pending);
  }
}

function walk_coresdk_workflow_activation_WorkflowActivationJob(
  o: coresdk.workflow_activation.IWorkflowActivationJob,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.initializeWorkflow;
    if (c != null) walk_coresdk_workflow_activation_InitializeWorkflow(c, visit, pending);
  }
  {
    const c = o.queryWorkflow;
    if (c != null) walk_coresdk_workflow_activation_QueryWorkflow(c, visit, pending);
  }
  {
    const c = o.signalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_SignalWorkflow(c, visit, pending);
  }
  {
    const c = o.resolveActivity;
    if (c != null) walk_coresdk_workflow_activation_ResolveActivity(c, visit, pending);
  }
  {
    const c = o.resolveChildWorkflowExecutionStart;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecutionStart(c, visit, pending);
  }
  {
    const c = o.resolveChildWorkflowExecution;
    if (c != null) walk_coresdk_workflow_activation_ResolveChildWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.resolveSignalExternalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_ResolveSignalExternalWorkflow(c, visit, pending);
  }
  {
    const c = o.resolveRequestCancelExternalWorkflow;
    if (c != null) walk_coresdk_workflow_activation_ResolveRequestCancelExternalWorkflow(c, visit, pending);
  }
  {
    const c = o.doUpdate;
    if (c != null) walk_coresdk_workflow_activation_DoUpdate(c, visit, pending);
  }
  {
    const c = o.resolveNexusOperationStart;
    if (c != null) walk_coresdk_workflow_activation_ResolveNexusOperationStart(c, visit, pending);
  }
  {
    const c = o.resolveNexusOperation;
    if (c != null) walk_coresdk_workflow_activation_ResolveNexusOperation(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_CompleteWorkflowExecution(
  o: coresdk.workflow_commands.ICompleteWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.result;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.result = one(r);
        })
      );
  }
}

function walk_coresdk_workflow_commands_ContinueAsNewWorkflowExecution(
  o: coresdk.workflow_commands.IContinueAsNewWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.arguments = many(r, a.length);
        })
      );
  }
  {
    const m = o.memo;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const c = o.searchAttributes;
    if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_FailWorkflowExecution(
  o: coresdk.workflow_commands.IFailWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_ModifyWorkflowProperties(
  o: coresdk.workflow_commands.IModifyWorkflowProperties,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.upsertedMemo;
    if (c != null) walk_temporal_api_common_v1_Memo(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_QueryResult(
  o: coresdk.workflow_commands.IQueryResult,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.succeeded;
    if (c != null) walk_coresdk_workflow_commands_QuerySuccess(c, visit, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_QuerySuccess(
  o: coresdk.workflow_commands.IQuerySuccess,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.response;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.response = one(r);
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleActivity(
  o: coresdk.workflow_commands.IScheduleActivity,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.arguments = many(r, a.length);
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleLocalActivity(
  o: coresdk.workflow_commands.IScheduleLocalActivity,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const a = o.arguments;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.arguments = many(r, a.length);
        })
      );
  }
}

function walk_coresdk_workflow_commands_ScheduleNexusOperation(
  o: coresdk.workflow_commands.IScheduleNexusOperation,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.input;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.input = one(r);
        })
      );
  }
}

function walk_coresdk_workflow_commands_SignalExternalWorkflowExecution(
  o: coresdk.workflow_commands.ISignalExternalWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.args;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.args = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_coresdk_workflow_commands_StartChildWorkflowExecution(
  o: coresdk.workflow_commands.IStartChildWorkflowExecution,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.input;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.input = many(r, a.length);
        })
      );
  }
  {
    const m = o.headers;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const m = o.memo;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
  {
    const c = o.searchAttributes;
    if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_UpdateResponse(
  o: coresdk.workflow_commands.IUpdateResponse,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.rejected;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
  {
    const p = o.completed;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.completed = one(r);
        })
      );
  }
}

function walk_coresdk_workflow_commands_UpsertWorkflowSearchAttributes(
  o: coresdk.workflow_commands.IUpsertWorkflowSearchAttributes,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.searchAttributes;
    if (c != null) walk_temporal_api_common_v1_SearchAttributes(c, visit, pending);
  }
}

function walk_coresdk_workflow_commands_WorkflowCommand(
  o: coresdk.workflow_commands.IWorkflowCommand,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.userMetadata;
    if (c != null) walk_temporal_api_sdk_v1_UserMetadata(c, visit, pending);
  }
  {
    const c = o.scheduleActivity;
    if (c != null) walk_coresdk_workflow_commands_ScheduleActivity(c, visit, pending);
  }
  {
    const c = o.respondToQuery;
    if (c != null) walk_coresdk_workflow_commands_QueryResult(c, visit, pending);
  }
  {
    const c = o.completeWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_CompleteWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.failWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_FailWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.continueAsNewWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_ContinueAsNewWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.startChildWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_StartChildWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.signalExternalWorkflowExecution;
    if (c != null) walk_coresdk_workflow_commands_SignalExternalWorkflowExecution(c, visit, pending);
  }
  {
    const c = o.scheduleLocalActivity;
    if (c != null) walk_coresdk_workflow_commands_ScheduleLocalActivity(c, visit, pending);
  }
  {
    const c = o.upsertWorkflowSearchAttributes;
    if (c != null) walk_coresdk_workflow_commands_UpsertWorkflowSearchAttributes(c, visit, pending);
  }
  {
    const c = o.modifyWorkflowProperties;
    if (c != null) walk_coresdk_workflow_commands_ModifyWorkflowProperties(c, visit, pending);
  }
  {
    const c = o.updateResponse;
    if (c != null) walk_coresdk_workflow_commands_UpdateResponse(c, visit, pending);
  }
  {
    const c = o.scheduleNexusOperation;
    if (c != null) walk_coresdk_workflow_commands_ScheduleNexusOperation(c, visit, pending);
  }
}

function walk_coresdk_workflow_completion_Failure(
  o: coresdk.workflow_completion.IFailure,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.failure;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
}

function walk_coresdk_workflow_completion_Success(
  o: coresdk.workflow_completion.ISuccess,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.commands;
    if (a) for (const v of a) walk_coresdk_workflow_commands_WorkflowCommand(v, visit, pending);
  }
}

function walk_coresdk_workflow_completion_WorkflowActivationCompletion(
  o: coresdk.workflow_completion.IWorkflowActivationCompletion,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.successful;
    if (c != null) walk_coresdk_workflow_completion_Success(c, visit, pending);
  }
  {
    const c = o.failed;
    if (c != null) walk_coresdk_workflow_completion_Failure(c, visit, pending);
  }
}

function walk_temporal_api_common_v1_Memo(
  o: temporal.api.common.v1.IMemo,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const m = o.fields;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_temporal_api_common_v1_Payloads(
  o: temporal.api.common.v1.IPayloads,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const a = o.payloads;
    if (a && a.length)
      pending.push(
        visit(a).then((r) => {
          o.payloads = many(r, a.length);
        })
      );
  }
}

function walk_temporal_api_common_v1_SearchAttributes(
  o: temporal.api.common.v1.ISearchAttributes,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const m = o.indexedFields;
    if (m)
      for (const [k, v] of Object.entries(m))
        pending.push(
          visit([v]).then((r) => {
            m[k] = one(r);
          })
        );
  }
}

function walk_temporal_api_failure_v1_ApplicationFailureInfo(
  o: temporal.api.failure.v1.IApplicationFailureInfo,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.details;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, visit, pending);
  }
}

function walk_temporal_api_failure_v1_CanceledFailureInfo(
  o: temporal.api.failure.v1.ICanceledFailureInfo,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.details;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, visit, pending);
  }
}

function walk_temporal_api_failure_v1_Failure(
  o: temporal.api.failure.v1.IFailure,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.encodedAttributes;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.encodedAttributes = one(r);
        })
      );
  }
  {
    const c = o.cause;
    if (c != null) walk_temporal_api_failure_v1_Failure(c, visit, pending);
  }
  {
    const c = o.applicationFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_ApplicationFailureInfo(c, visit, pending);
  }
  {
    const c = o.timeoutFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_TimeoutFailureInfo(c, visit, pending);
  }
  {
    const c = o.canceledFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_CanceledFailureInfo(c, visit, pending);
  }
  {
    const c = o.resetWorkflowFailureInfo;
    if (c != null) walk_temporal_api_failure_v1_ResetWorkflowFailureInfo(c, visit, pending);
  }
}

function walk_temporal_api_failure_v1_ResetWorkflowFailureInfo(
  o: temporal.api.failure.v1.IResetWorkflowFailureInfo,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.lastHeartbeatDetails;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, visit, pending);
  }
}

function walk_temporal_api_failure_v1_TimeoutFailureInfo(
  o: temporal.api.failure.v1.ITimeoutFailureInfo,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const c = o.lastHeartbeatDetails;
    if (c != null) walk_temporal_api_common_v1_Payloads(c, visit, pending);
  }
}

function walk_temporal_api_sdk_v1_UserMetadata(
  o: temporal.api.sdk.v1.IUserMetadata,
  visit: Visit,
  pending: Promise<unknown>[]
): void {
  {
    const p = o.summary;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.summary = one(r);
        })
      );
  }
  {
    const p = o.details;
    if (p != null)
      pending.push(
        visit([p]).then((r) => {
          o.details = one(r);
        })
      );
  }
}
