[package]
name = "bridge-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"

[dev-dependencies]
temporal-sdk-typescript-bridge = { path = ".." }
