[package]
name = "temporal-sdk-node-bridge"
version = "0.1.0"
authors = ["Roey Berman <roey@temporal.io>"]
license = "MIT"
edition = "2018"
exclude = ["index.node", "sdk-core"]

[lib]
name = "temporal_sdk_node_bridge"
crate-type = ["cdylib"]

[dependencies]
futures = { version = "0.3", features = ["executor"] }
neon = { version = "0.8.0", default-features = false, features = ["napi-4", "event-queue-api"] }
prost = "0.7"
prost-types = "0.7"
tokio = "1.4.0"

[dependencies.temporal-sdk-core]
# TODO: revert back to *, can't now because of this error: prerelease package needs to be specified explicitly
# version = "*"
version = "0.1.0-alpha.1"
path = "./sdk-core"
