import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import * as protobuf from 'protobufjs';

const repoRoot = resolve(__dirname, '..');
const protoBaseDir = resolve(repoRoot, 'packages/core-bridge/sdk-core/crates/common/protos');
const workflowSystemNexusDir = resolve(repoRoot, 'packages/workflow/system-nexus');
const witPath = resolve(workflowSystemNexusDir, 'wit/workflow-service.wit');
const witDepsPath = resolve(workflowSystemNexusDir, 'wit/deps');
const supportPath = resolve(workflowSystemNexusDir, 'typescript/temporal_model_converters.ts');
const workflowOutputDir = resolve(repoRoot, 'packages/workflow/src/nexus/system/generated');
const workerVisitorPath = resolve(repoRoot, 'packages/worker/src/system-nexus-payload-visitor.ts');
const descriptorPath = resolve(repoRoot, 'build/system-nexus/temporal_api.bin');

interface OperationInfo {
  service: string;
  operation: string;
  inputType: string;
  outputType: string;
}

interface MessageInfo {
  fullName: string;
  descriptor: any;
}

function run(command: string, args: string[]): void {
  execFileSync(command, args, { cwd: repoRoot, stdio: 'inherit' });
}

function commandExists(command: string): boolean {
  return spawnSync(command, ['--help'], { stdio: 'ignore' }).status === 0;
}

function nexGenCommand(): string {
  if (process.env.NEX_GEN_BIN) return process.env.NEX_GEN_BIN;
  if (!commandExists('nex-gen')) {
    run('cargo', ['install', '--locked', 'nex-gen', '--force']);
  }
  return 'nex-gen';
}

function newestMtime(paths: string[]): number {
  let newest = 0;
  for (const path of paths) {
    if (!existsSync(path)) continue;
    const stat = statSync(path);
    if (stat.isDirectory()) continue;
    newest = Math.max(newest, stat.mtimeMs);
  }
  return newest;
}

function maybeSkip(): boolean {
  const outputs = [
    resolve(workflowOutputDir, 'index.ts'),
    resolve(workflowOutputDir, 'service.ts'),
    resolve(workflowOutputDir, 'operations/signal-with-start-workflow.ts'),
    workerVisitorPath,
  ];
  if (outputs.some((path) => !existsSync(path))) return false;
  const outputMtime = Math.min(...outputs.map((path) => statSync(path).mtimeMs));
  const inputs = [
    witPath,
    supportPath,
    resolve(witDepsPath, 'nexus-temporal-types/model.wit'),
    resolve(repoRoot, 'scripts/gen-system-nexus.ts'),
  ];
  if (process.env.NEX_GEN_BIN && existsSync(process.env.NEX_GEN_BIN)) inputs.push(process.env.NEX_GEN_BIN);
  return newestMtime(inputs) < outputMtime;
}

function buildDescriptorSet(): void {
  mkdirSync(dirname(descriptorPath), { recursive: true });
  run('protoc', [
    '-I',
    resolve(protoBaseDir, 'api_upstream'),
    '-I',
    protoBaseDir,
    '--include_imports',
    `--descriptor_set_out=${descriptorPath}`,
    resolve(protoBaseDir, 'api_upstream/temporal/api/workflowservice/v1/request_response.proto'),
  ]);
}

function generateNexGenTypescript(): void {
  rmSync(workflowOutputDir, { recursive: true, force: true });
  mkdirSync(workflowOutputDir, { recursive: true });
  run(nexGenCommand(), [
    'generate',
    '--lang',
    'typescript',
    '--input',
    witPath,
    '--input',
    witDepsPath,
    '--support-file',
    supportPath,
    '--descriptors',
    descriptorPath,
    '--output',
    workflowOutputDir,
  ]);
}

function postProcessGeneratedWorkflowFiles(): void {
  for (const path of [
    resolve(workflowOutputDir, 'index.ts'),
    resolve(workflowOutputDir, 'models.ts'),
    resolve(workflowOutputDir, 'support.ts'),
    resolve(workflowOutputDir, 'service.ts'),
    resolve(workflowOutputDir, 'operations/signal-with-start-workflow.ts'),
  ]) {
    let source = readFileSync(path, 'utf8');
    source = source.replace(/((?:from|export .* from) ['"]\.{1,2}[^'"]*)\.ts(['"])/g, '$1$2');
    source = source.replace(/from ['"]@temporalio\/workflow['"]/g, () =>
      path.includes('/operations/') ? "from '../workflow-exports'" : "from './workflow-exports'"
    );
    writeFileSync(path, source);
  }

  writeFileSync(
    resolve(workflowOutputDir, 'workflow-exports.ts'),
    [
      '// Generated by scripts/gen-system-nexus.ts. DO NOT EDIT!',
      '',
      "export { createNexusServiceClient } from '../../../nexus';",
      "export { getExternalWorkflowHandle, workflowInfo } from '../../../workflow';",
      "export type { ExternalWorkflowHandle } from '../../../workflow-handle';",
      "export type { SignalDefinition } from '@temporalio/common';",
      '',
    ].join('\n')
  );
}

async function loadDescriptorMessages(): Promise<Map<string, MessageInfo>> {
  const root = new protobuf.Root();
  const roots = [
    resolve(protoBaseDir, 'api_upstream'),
    resolve(protoBaseDir, 'testsrv_upstream'),
    resolve(protoBaseDir, 'local'),
    resolve(protoBaseDir, 'api_cloud_upstream'),
    protoBaseDir,
  ];
  root.resolvePath = (_origin, target) => {
    for (const base of roots) {
      const path = resolve(base, target);
      if (existsSync(path)) return path;
    }
    return target;
  };
  await root.load(resolve(protoBaseDir, 'api_upstream/google/protobuf/descriptor.proto'), { keepCase: true });
  const descriptorSetType = root.lookupType('google.protobuf.FileDescriptorSet');
  const descriptorSet = descriptorSetType.toObject(descriptorSetType.decode(readFileSync(descriptorPath)), {
    defaults: false,
    enums: String,
    longs: String,
  }) as any;

  const messages = new Map<string, MessageInfo>();
  for (const file of descriptorSet.file ?? []) {
    for (const message of file.message_type ?? []) {
      addMessage(messages, file.package ?? '', message);
    }
  }
  return messages;
}

function addMessage(messages: Map<string, MessageInfo>, prefix: string, descriptor: any): void {
  const fullName = prefix ? `${prefix}.${descriptor.name}` : descriptor.name;
  messages.set(fullName, { fullName, descriptor });
  for (const nested of descriptor.nested_type ?? []) addMessage(messages, fullName, nested);
}

function getMessage(messages: Map<string, MessageInfo>, fullName: string): MessageInfo {
  const message = messages.get(fullName.replace(/^\./, ''));
  if (!message) throw new Error(`No protobuf message descriptor found for ${fullName}`);
  return message;
}

function isPayload(message: MessageInfo): boolean {
  return message.fullName === 'temporal.api.common.v1.Payload';
}

function isPayloads(message: MessageInfo): boolean {
  return message.fullName === 'temporal.api.common.v1.Payloads';
}

function isSearchAttributes(message: MessageInfo): boolean {
  return message.fullName === 'temporal.api.common.v1.SearchAttributes';
}

function isMapEntry(message: MessageInfo): boolean {
  return message.descriptor.options?.map_entry === true || message.descriptor.options?.mapEntry === true;
}

function tryGetFieldMessage(field: any, messages: Map<string, MessageInfo>): MessageInfo | undefined {
  if (field.type !== 'TYPE_MESSAGE' || !field.type_name) return undefined;
  return messages.get(String(field.type_name).replace(/^\./, ''));
}

function containsPayload(
  message: MessageInfo,
  messages: Map<string, MessageInfo>,
  memo = new Map<string, boolean>(),
  visiting = new Set<string>()
): boolean {
  if (isSearchAttributes(message)) return false;
  if (isPayload(message) || isPayloads(message)) return true;
  const cached = memo.get(message.fullName);
  if (cached != null) return cached;
  if (visiting.has(message.fullName)) return false;
  visiting.add(message.fullName);
  let result = false;
  for (const field of message.descriptor.field ?? []) {
    const fieldMessage = tryGetFieldMessage(field, messages);
    if (!fieldMessage || isSearchAttributes(fieldMessage)) continue;
    if (isMapEntry(fieldMessage)) {
      const valueField = (fieldMessage.descriptor.field ?? []).find((candidate: any) => candidate.name === 'value');
      const valueMessage = valueField ? tryGetFieldMessage(valueField, messages) : undefined;
      if (valueMessage && containsPayload(valueMessage, messages, memo, visiting)) {
        result = true;
        break;
      }
    } else if (containsPayload(fieldMessage, messages, memo, visiting)) {
      result = true;
      break;
    }
  }
  visiting.delete(message.fullName);
  memo.set(message.fullName, result);
  return result;
}

function propertyName(protoName: string): string {
  return protoName.replace(/_([a-zA-Z0-9])/g, (_match, ch: string) => ch.toUpperCase());
}

function visitMethodName(message: MessageInfo): string {
  return `visit_${message.fullName.replace(/[^A-Za-z0-9_]/g, '_')}`;
}

function localName(message: MessageInfo, field: any, suffix: string): string {
  return `${message.fullName}_${field.name}_${suffix}`.replace(/[^A-Za-z0-9_]/g, '_');
}

function referencedMessagesWithPayloads(
  message: MessageInfo,
  messages: Map<string, MessageInfo>,
  memo: Map<string, boolean>
): MessageInfo[] {
  const referenced: MessageInfo[] = [];
  for (const field of message.descriptor.field ?? []) {
    const fieldMessage = tryGetFieldMessage(field, messages);
    if (!fieldMessage || isPayload(fieldMessage) || isSearchAttributes(fieldMessage)) continue;
    if (isMapEntry(fieldMessage)) {
      const valueField = (fieldMessage.descriptor.field ?? []).find((candidate: any) => candidate.name === 'value');
      const valueMessage = valueField ? tryGetFieldMessage(valueField, messages) : undefined;
      if (
        valueMessage &&
        !isPayload(valueMessage) &&
        !isSearchAttributes(valueMessage) &&
        containsPayload(valueMessage, messages, memo)
      ) {
        referenced.push(valueMessage);
      }
    } else if (containsPayload(fieldMessage, messages, memo)) {
      referenced.push(fieldMessage);
    }
  }
  return referenced;
}

function visitFieldLines(
  message: MessageInfo,
  messages: Map<string, MessageInfo>,
  memo: Map<string, boolean>
): string[] {
  const lines: string[] = [];
  for (const field of message.descriptor.field ?? []) {
    const fieldMessage = tryGetFieldMessage(field, messages);
    if (!fieldMessage || isSearchAttributes(fieldMessage)) continue;
    const prop = propertyName(field.name);
    if (isMapEntry(fieldMessage)) {
      const valueField = (fieldMessage.descriptor.field ?? []).find((candidate: any) => candidate.name === 'value');
      const valueMessage = valueField ? tryGetFieldMessage(valueField, messages) : undefined;
      if (!valueMessage || isSearchAttributes(valueMessage) || !containsPayload(valueMessage, messages, memo)) continue;
      const mapVar = localName(message, field, 'map');
      const keyVar = localName(message, field, 'key');
      lines.push(`const ${mapVar} = value.${prop} as Record<string, any> | null | undefined;`);
      lines.push(`if (${mapVar} != null) {`);
      lines.push(`  for (const ${keyVar} of Object.keys(${mapVar})) {`);
      lines.push(`    const item = ${mapVar}[${keyVar}];`);
      lines.push(`    if (item == null) continue;`);
      if (isPayload(valueMessage)) {
        lines.push(`    ${mapVar}[${keyVar}] = await visitPayload(item as Payload);`);
      } else if (isPayloads(valueMessage)) {
        lines.push(`    if (item.payloads != null) item.payloads = await visitPayloads(item.payloads as Payload[]);`);
      } else {
        lines.push(`    await ${visitMethodName(valueMessage)}(item, visitPayload, visitPayloads);`);
      }
      lines.push(`  }`);
      lines.push(`}`);
      continue;
    }
    if (!containsPayload(fieldMessage, messages, memo)) continue;
    const repeated = field.label === 'LABEL_REPEATED';
    if (isPayload(fieldMessage)) {
      if (repeated) {
        lines.push(`if (value.${prop} != null) value.${prop} = await visitPayloads(value.${prop} as Payload[]);`);
      } else {
        lines.push(`if (value.${prop} != null) value.${prop} = await visitPayload(value.${prop} as Payload);`);
      }
    } else if (isPayloads(fieldMessage)) {
      if (repeated) {
        lines.push(`for (const payloads of value.${prop} ?? []) {`);
        lines.push(
          `  if (payloads.payloads != null) payloads.payloads = await visitPayloads(payloads.payloads as Payload[]);`
        );
        lines.push(`}`);
      } else {
        lines.push(
          `if (value.${prop}?.payloads != null) value.${prop}.payloads = await visitPayloads(value.${prop}.payloads as Payload[]);`
        );
      }
    } else if (repeated) {
      lines.push(
        `for (const item of value.${prop} ?? []) await ${visitMethodName(
          fieldMessage
        )}(item, visitPayload, visitPayloads);`
      );
    } else {
      lines.push(
        `if (value.${prop} != null) await ${visitMethodName(fieldMessage)}(value.${prop}, visitPayload, visitPayloads);`
      );
    }
  }
  return lines;
}

function emitVisitMethod(
  message: MessageInfo,
  messages: Map<string, MessageInfo>,
  memo: Map<string, boolean>,
  emitted: Set<string>,
  out: string[]
): void {
  if (emitted.has(message.fullName)) return;
  emitted.add(message.fullName);
  for (const referenced of referencedMessagesWithPayloads(message, messages, memo)) {
    emitVisitMethod(referenced, messages, memo, emitted, out);
  }
  out.push(
    `async function ${visitMethodName(
      message
    )}(value: any, visitPayload: PayloadVisitor, visitPayloads: PayloadsVisitor): Promise<void> {`
  );
  for (const line of visitFieldLines(message, messages, memo)) out.push(`  ${line}`);
  out.push('}');
  out.push('');
}

function operationConstants(operations: OperationInfo[]): string {
  return `export const SYSTEM_NEXUS_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;`;
}

async function loadGeneratedOperationRegistry(): Promise<OperationInfo[]> {
  const servicePath = resolve(workflowOutputDir, 'service.ts');
  const serviceModule = await import(`${pathToFileURL(servicePath).href}?mtime=${statSync(servicePath).mtimeMs}`);
  const registry = serviceModule.operationRegistry;
  if (!Array.isArray(registry) || registry.length === 0) {
    throw new Error('Generated system Nexus service did not export a non-empty operationRegistry');
  }

  return registry.map((operation, index) => {
    for (const field of ['service', 'operation', 'inputType', 'outputType'] as const) {
      if (typeof operation?.[field] !== 'string' || operation[field].length === 0) {
        throw new Error(`Generated operationRegistry[${index}].${field} must be a non-empty string`);
      }
    }
    return {
      service: operation.service,
      operation: operation.operation,
      inputType: operation.inputType,
      outputType: operation.outputType,
    };
  });
}

function generateWorkerVisitor(operations: OperationInfo[], messages: Map<string, MessageInfo>): void {
  const memo = new Map<string, boolean>();
  const emitted = new Set<string>();
  const methods: string[] = [];
  for (const operation of operations) {
    emitVisitMethod(getMessage(messages, operation.inputType), messages, memo, emitted, methods);
    emitVisitMethod(getMessage(messages, operation.outputType), messages, memo, emitted, methods);
  }

  writeFileSync(
    workerVisitorPath,
    [
      '// Generated by scripts/gen-system-nexus.ts. DO NOT EDIT!',
      '',
      "import type { Payload } from '@temporalio/common';",
      '',
      'type PayloadVisitor = (payload: Payload) => Promise<Payload>;',
      'type PayloadsVisitor = (payloads: Payload[]) => Promise<Payload[]>;',
      '',
      operationConstants(operations),
      '',
      'export async function visitSystemNexusPayloads(',
      '  messageTypeName: string,',
      '  message: any,',
      '  visitPayload: PayloadVisitor,',
      '  visitPayloads: PayloadsVisitor',
      '): Promise<void> {',
      ...operations.flatMap((operation) => [
        `  if (messageTypeName === ${JSON.stringify(operation.inputType)}) {`,
        `    await ${visitMethodName(
          getMessage(messages, operation.inputType)
        )}(message, visitPayload, visitPayloads);`,
        '    return;',
        '  }',
        `  if (messageTypeName === ${JSON.stringify(operation.outputType)}) {`,
        `    await ${visitMethodName(
          getMessage(messages, operation.outputType)
        )}(message, visitPayload, visitPayloads);`,
        '    return;',
        '  }',
      ]),
      '  throw new Error(`Unrecognized system Nexus proto message type: ${messageTypeName}`);',
      '}',
      '',
      methods.join('\n'),
    ].join('\n')
  );
}

async function main(): Promise<void> {
  for (const path of [witPath, witDepsPath, supportPath]) {
    if (!existsSync(path)) throw new Error(`Missing system Nexus input: ${path}`);
  }
  if (maybeSkip()) return;
  buildDescriptorSet();
  generateNexGenTypescript();
  postProcessGeneratedWorkflowFiles();
  const operations = await loadGeneratedOperationRegistry();
  const messages = await loadDescriptorMessages();
  generateWorkerVisitor(operations, messages);

  const prettier = spawnSync('pnpm', ['exec', 'prettier', '--write', workflowOutputDir, workerVisitorPath], {
    cwd: repoRoot,
    stdio: 'inherit',
  });
  if (prettier.status !== 0) throw new Error('prettier failed for generated system Nexus files');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
