// Generated by scripts/gen-system-nexus.ts. DO NOT EDIT!

import type { Payload } from '@temporalio/common';

type PayloadVisitor = (payload: Payload) => Promise<Payload>;
type PayloadsVisitor = (payloads: Payload[]) => Promise<Payload[]>;

export const SYSTEM_NEXUS_OPERATIONS = [
  {
    service: 'temporal.api.workflowservice.v1.WorkflowService',
    operation: 'SignalWithStartWorkflowExecution',
    inputType: 'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest',
    outputType: 'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse',
  },
] as const;

export async function visitSystemNexusPayloads(
  messageTypeName: string,
  message: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (messageTypeName === 'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest') {
    await visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionRequest(
      message,
      visitPayload,
      visitPayloads
    );
    return;
  }
  if (messageTypeName === 'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse') {
    await visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionResponse(
      message,
      visitPayload,
      visitPayloads
    );
    return;
  }
  throw new Error(`Unrecognized system Nexus proto message type: ${messageTypeName}`);
}

async function visit_temporal_api_common_v1_Payloads(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (value.payloads != null) value.payloads = await visitPayloads(value.payloads as Payload[]);
}

async function visit_temporal_api_common_v1_Memo(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  const temporal_api_common_v1_Memo_fields_map = value.fields as Record<string, any> | null | undefined;
  if (temporal_api_common_v1_Memo_fields_map != null) {
    for (const temporal_api_common_v1_Memo_fields_key of Object.keys(temporal_api_common_v1_Memo_fields_map)) {
      const item = temporal_api_common_v1_Memo_fields_map[temporal_api_common_v1_Memo_fields_key];
      if (item == null) continue;
      temporal_api_common_v1_Memo_fields_map[temporal_api_common_v1_Memo_fields_key] = await visitPayload(
        item as Payload
      );
    }
  }
}

async function visit_temporal_api_common_v1_Header(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  const temporal_api_common_v1_Header_fields_map = value.fields as Record<string, any> | null | undefined;
  if (temporal_api_common_v1_Header_fields_map != null) {
    for (const temporal_api_common_v1_Header_fields_key of Object.keys(temporal_api_common_v1_Header_fields_map)) {
      const item = temporal_api_common_v1_Header_fields_map[temporal_api_common_v1_Header_fields_key];
      if (item == null) continue;
      temporal_api_common_v1_Header_fields_map[temporal_api_common_v1_Header_fields_key] = await visitPayload(
        item as Payload
      );
    }
  }
}

async function visit_temporal_api_sdk_v1_UserMetadata(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (value.summary != null) value.summary = await visitPayload(value.summary as Payload);
  if (value.details != null) value.details = await visitPayload(value.details as Payload);
}

async function visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionRequest(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (value.input?.payloads != null) value.input.payloads = await visitPayloads(value.input.payloads as Payload[]);
  if (value.signalInput?.payloads != null)
    value.signalInput.payloads = await visitPayloads(value.signalInput.payloads as Payload[]);
  if (value.memo != null) await visit_temporal_api_common_v1_Memo(value.memo, visitPayload, visitPayloads);
  if (value.header != null) await visit_temporal_api_common_v1_Header(value.header, visitPayload, visitPayloads);
  if (value.userMetadata != null)
    await visit_temporal_api_sdk_v1_UserMetadata(value.userMetadata, visitPayload, visitPayloads);
}

async function visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionResponse(
  value: any,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {}
