// Generated by scripts/gen-system-nexus.ts. DO NOT EDIT!

import type { Payload } from '@temporalio/common';
import { temporal } from '@temporalio/proto';

export interface SystemNexusMessageByType {
  'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest': temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest;
  'temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse': temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse;
}

export type SystemNexusMessage = SystemNexusMessageByType[keyof SystemNexusMessageByType];

type PayloadVisitor = (payload: Payload) => Promise<Payload>;
type PayloadsVisitor = (payloads: Payload[]) => Promise<Payload[]>;

export async function visitSystemNexusPayloads(
  message: SystemNexusMessage,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (message instanceof temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest) {
    await visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionRequest(
      message,
      visitPayload,
      visitPayloads
    );
    return;
  } else if (message instanceof temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse) {
    await visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionResponse(
      message,
      visitPayload,
      visitPayloads
    );
    return;
  }
  throw new Error('Unrecognized system Nexus proto message type');
}

async function visit_temporal_api_common_v1_Memo(
  value: temporal.api.common.v1.IMemo,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  const temporal_api_common_v1_Memo_fields_map = value.fields;
  if (temporal_api_common_v1_Memo_fields_map != null) {
    for (const temporal_api_common_v1_Memo_fields_key of Object.keys(temporal_api_common_v1_Memo_fields_map)) {
      const item = temporal_api_common_v1_Memo_fields_map[temporal_api_common_v1_Memo_fields_key];
      if (item == null) continue;
      temporal_api_common_v1_Memo_fields_map[temporal_api_common_v1_Memo_fields_key] = await visitPayload(item);
    }
  }
}

async function visit_temporal_api_common_v1_Header(
  value: temporal.api.common.v1.IHeader,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  const temporal_api_common_v1_Header_fields_map = value.fields;
  if (temporal_api_common_v1_Header_fields_map != null) {
    for (const temporal_api_common_v1_Header_fields_key of Object.keys(temporal_api_common_v1_Header_fields_map)) {
      const item = temporal_api_common_v1_Header_fields_map[temporal_api_common_v1_Header_fields_key];
      if (item == null) continue;
      temporal_api_common_v1_Header_fields_map[temporal_api_common_v1_Header_fields_key] = await visitPayload(item);
    }
  }
}

async function visit_temporal_api_sdk_v1_UserMetadata(
  value: temporal.api.sdk.v1.IUserMetadata,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (value.summary != null) value.summary = await visitPayload(value.summary);
  if (value.details != null) value.details = await visitPayload(value.details);
}

async function visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionRequest(
  value: temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionRequest,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {
  if (value.input?.payloads != null) value.input.payloads = await visitPayloads(value.input.payloads);
  if (value.signalInput?.payloads != null) value.signalInput.payloads = await visitPayloads(value.signalInput.payloads);
  if (value.memo != null) await visit_temporal_api_common_v1_Memo(value.memo, visitPayload, visitPayloads);
  if (value.header != null) await visit_temporal_api_common_v1_Header(value.header, visitPayload, visitPayloads);
  if (value.userMetadata != null)
    await visit_temporal_api_sdk_v1_UserMetadata(value.userMetadata, visitPayload, visitPayloads);
}

async function visit_temporal_api_workflowservice_v1_SignalWithStartWorkflowExecutionResponse(
  value: temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionResponse,
  visitPayload: PayloadVisitor,
  visitPayloads: PayloadsVisitor
): Promise<void> {}
