%% Activation diagram for Worker with `debugMode` option on
sequenceDiagram
    participant Server
    participant Core as Rust Core
    participant MT as Node Main Thread
    participant VM as Workflow VM Sandbox

    MT->>+Core: Poll Workflow Activation
    opt No pending work
        Core->>+Server: Poll Workflow Task
        Server-->>-Core: Respond with Workflow Task
    end
    Core->>-MT: Respond with Activation
    MT->>MT: Decode Payloads
    loop patches, signals, updates, completions, queries as jobs
        MT->>VM: Activate(jobs)
        VM->>VM: Run Microtasks
        MT->>VM: Try Unblock Conditions
    end
    MT->>VM: Collect Commands
    MT->>MT: Encode Payloads
    MT->>+VM: Collect Sink Calls
    VM-->>-MT: Respond with Sink Calls
    MT->>MT: Run Sink Functions
    MT->>Core: Complete Activation
    opt Completed Workflow Task   
        Core->>Server: Complete Workflow Task
    end

