// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file messages.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file messages.proto.
 */
export const file_messages: GenFile = /*@__PURE__*/
  fileDesc("Cg5tZXNzYWdlcy5wcm90byIvChJQcm90b0FjdGl2aXR5SW5wdXQSDAoEbmFtZRgBIAEoCRILCgNhZ2UYAiABKAUiJwoTUHJvdG9BY3Rpdml0eVJlc3VsdBIQCghzZW50ZW5jZRgBIAEoCSIdCg1CaW5hcnlNZXNzYWdlEgwKBGRhdGEYASABKAwiPAoHV3JhcHBlchIiCgVpbm5lchgBIAEoCzITLlByb3RvQWN0aXZpdHlJbnB1dBINCgVsYWJlbBgCIAEoCSJhCgxPbmVvZk1lc3NhZ2USDgoEdGV4dBgBIAEoCUgAEhAKBm51bWJlchgCIAEoBUgAEiUKBm5lc3RlZBgDIAEoCzITLlByb3RvQWN0aXZpdHlJbnB1dEgAQggKBmNob2ljZSK/AQoKTWFwTWVzc2FnZRIpCgdlbnRyaWVzGAEgAygLMhguTWFwTWVzc2FnZS5FbnRyaWVzRW50cnkSJwoGY291bnRzGAIgAygLMhcuTWFwTWVzc2FnZS5Db3VudHNFbnRyeRouCgxFbnRyaWVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARotCgtDb3VudHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgBIjQKDk51bWJlcnNBbmRFbnVtEgsKA2JpZxgBIAEoAxIVCgVjb2xvchgCIAEoDjIGLkNvbG9yKk4KBUNvbG9yEhUKEUNPTE9SX1VOU1BFQ0lGSUVEEAASDQoJQ09MT1JfUkVEEAESDwoLQ09MT1JfR1JFRU4QAhIOCgpDT0xPUl9CTFVFEANiBnByb3RvMw");

/**
 * @generated from message ProtoActivityInput
 */
export type ProtoActivityInput = Message<"ProtoActivityInput"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 age = 2;
   */
  age: number;
};

/**
 * Describes the message ProtoActivityInput.
 * Use `create(ProtoActivityInputSchema)` to create a new message.
 */
export const ProtoActivityInputSchema: GenMessage<ProtoActivityInput> = /*@__PURE__*/
  messageDesc(file_messages, 0);

/**
 * @generated from message ProtoActivityResult
 */
export type ProtoActivityResult = Message<"ProtoActivityResult"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message ProtoActivityResult.
 * Use `create(ProtoActivityResultSchema)` to create a new message.
 */
export const ProtoActivityResultSchema: GenMessage<ProtoActivityResult> = /*@__PURE__*/
  messageDesc(file_messages, 1);

/**
 * @generated from message BinaryMessage
 */
export type BinaryMessage = Message<"BinaryMessage"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message BinaryMessage.
 * Use `create(BinaryMessageSchema)` to create a new message.
 */
export const BinaryMessageSchema: GenMessage<BinaryMessage> = /*@__PURE__*/
  messageDesc(file_messages, 2);

/**
 * @generated from message Wrapper
 */
export type Wrapper = Message<"Wrapper"> & {
  /**
   * @generated from field: ProtoActivityInput inner = 1;
   */
  inner?: ProtoActivityInput | undefined;

  /**
   * @generated from field: string label = 2;
   */
  label: string;
};

/**
 * Describes the message Wrapper.
 * Use `create(WrapperSchema)` to create a new message.
 */
export const WrapperSchema: GenMessage<Wrapper> = /*@__PURE__*/
  messageDesc(file_messages, 3);

/**
 * @generated from message OneofMessage
 */
export type OneofMessage = Message<"OneofMessage"> & {
  /**
   * @generated from oneof OneofMessage.choice
   */
  choice: {
    /**
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * @generated from field: int32 number = 2;
     */
    value: number;
    case: "number";
  } | {
    /**
     * @generated from field: ProtoActivityInput nested = 3;
     */
    value: ProtoActivityInput;
    case: "nested";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message OneofMessage.
 * Use `create(OneofMessageSchema)` to create a new message.
 */
export const OneofMessageSchema: GenMessage<OneofMessage> = /*@__PURE__*/
  messageDesc(file_messages, 4);

/**
 * @generated from message MapMessage
 */
export type MapMessage = Message<"MapMessage"> & {
  /**
   * @generated from field: map<string, string> entries = 1;
   */
  entries: { [key: string]: string };

  /**
   * @generated from field: map<string, int32> counts = 2;
   */
  counts: { [key: string]: number };
};

/**
 * Describes the message MapMessage.
 * Use `create(MapMessageSchema)` to create a new message.
 */
export const MapMessageSchema: GenMessage<MapMessage> = /*@__PURE__*/
  messageDesc(file_messages, 5);

/**
 * Exercises int64 (encoded as string in proto3 JSON) and an enum.
 *
 * @generated from message NumbersAndEnum
 */
export type NumbersAndEnum = Message<"NumbersAndEnum"> & {
  /**
   * @generated from field: int64 big = 1;
   */
  big: bigint;

  /**
   * @generated from field: Color color = 2;
   */
  color: Color;
};

/**
 * Describes the message NumbersAndEnum.
 * Use `create(NumbersAndEnumSchema)` to create a new message.
 */
export const NumbersAndEnumSchema: GenMessage<NumbersAndEnum> = /*@__PURE__*/
  messageDesc(file_messages, 6);

/**
 * @generated from enum Color
 */
export enum Color {
  /**
   * @generated from enum value: COLOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COLOR_RED = 1;
   */
  RED = 1,

  /**
   * @generated from enum value: COLOR_GREEN = 2;
   */
  GREEN = 2,

  /**
   * @generated from enum value: COLOR_BLUE = 3;
   */
  BLUE = 3,
}

/**
 * Describes the enum Color.
 */
export const ColorSchema: GenEnum<Color> = /*@__PURE__*/
  enumDesc(file_messages, 0);

