// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file uppercase.proto (package Uppercase, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file uppercase.proto.
 */
export const file_uppercase: GenFile = /*@__PURE__*/
  fileDesc("Cg91cHBlcmNhc2UucHJvdG8SCVVwcGVyY2FzZSIcCgxVcHBlck1lc3NhZ2USDAoEbmFtZRgBIAEoCWIGcHJvdG8z");

/**
 * @generated from message Uppercase.UpperMessage
 */
export type UpperMessage = Message<"Uppercase.UpperMessage"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message Uppercase.UpperMessage.
 * Use `create(UpperMessageSchema)` to create a new message.
 */
export const UpperMessageSchema: GenMessage<UpperMessage> = /*@__PURE__*/
  messageDesc(file_uppercase, 0);

