version: '3.5'

services:
  cassandra:
    image: cassandra:3.11
    logging:
      driver: none
    ports:
      - '9042:9042'

  temporal:
    image: temporalio/auto-setup:1.11.0
    logging:
      driver: none
    ports:
      - '7233:7233'
      - '7234:7234'
      - '7235:7235'
      - '7239:7239'
      - '6933:6933'
      - '6934:6934'
      - '6935:6935'
      - '6939:6939'
    environment:
      - 'CASSANDRA_SEEDS=cassandra'
      - 'DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml'
    depends_on:
      - cassandra

  temporal-web:
    image: temporalio/web:1.11.0
    logging:
      driver: none
    ports:
      - '8088:8088'
    environment:
      - 'TEMPORAL_GRPC_ENDPOINT=temporal:7233'
    depends_on:
      - temporal


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ../../etc/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ../../etc/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

