version: '3.5'

services:
  test-container:
    build:
      context: ../../
      dockerfile: .buildkite/docker/Dockerfile
    command: /bin/sh -c ".buildkite/docker/build"
    environment:
      - 'TEMPORAL_SERVICE_ADDRESS=http://temporal:7233'
      - 'TEMPORAL_TESTING_SERVER_URL=temporal:7233'
    depends_on:
      - temporal
    volumes:
      - '../../:/sdk-typescript'
